.TH CFM 1 "2022 April 28"
.
.SH NAME
cfm \- cactus file manager
.
.SH SYNOPSIS
.B cfm
.RI [ DIR ]
.
.SH DESCRIPTION
.B cfm
is a simple, clean, fast TUI file manager.
.
.SH OPTIONS
.TP
.I DIR
Directory to open
.B cfm
in, or the working directory if not specified.
.
.SH CONFIGURATION
Copy
.I config.def.h
to
.I config.h
and modify as needed to configure at build-time.
By default,
.B cfm
will attempt to read the
.BR EDITOR , SHELL ", and " OPENER
environment variables.
If it is preferable for
.B cfm
to use a different value for any of these, it can be specified by prepending
.B CFM_
to any of the variables.
.B cfm
will also check for the
.B CFM_TMP
environment variable for a location for its temp directory.
If the variable is not set and
.B CFM_TMP
was not set in
.IR config.h ,
it will attempt to use
.IR /tmp/cfmtmp .
If the temporary directory cannot be created, then
.B cfm
will disable cut/paste and deletions will be permanent (no undo).
If the
.B CD_ON_CLOSE
option is not enabled at compile-time (default off),
.B cfm
will also check for the presence of the
.B CFM_CD_ON_CLOSE
environment variable, which should contain the path to a file into which it can
save its current working directory when quit with
.BR Q .
.
.SH USAGE
Note: Arrow keys work the same as hjkl.
.TP
.B j k
Move up/down.
.
.TP
.B PgUp PgDn
Move up/down by one full screen.
.
.TP
.B h l
Move left/right.
.
.TP
.B gg
Move to top.
.
.TP
.B G
Move to bottom.
.
.TP
.B ~
Move to user home directory.
.
.TP
.B /
Move to system root directory.
.
.TP
.B l
Open file using
.BR EDITOR ,
or change into directory.
.
.TP
.B o
Open file or directory with
.BR OPENER .
.
.TP
.B RET
Works like
.B o
if
.I ENTER_OPENS
is enabled, else works like
.BR l .
.
.TP
.B .
Toggles visibility of dotfiles.
.
.TP
.B e
Open file or directory in
.IR EDITOR .
.
.TP
.B r
Reload directory.
.
.TP
.B S
Spawn a shell (defined by
.BR SHELL
in a directory.
.
.TP
.B T
Create a new file, opening
.B EDITOR
to enter a filename.
.
.TP
.B M
Create a new directory, opening
.B EDITOR
to enter a directory name.
.
.TP
.B R
Rename a file by opening
.B EDITOR
to edit the filename.
.
.IP
Note: For
.BR T ,
.BR M ,
and
.BR R ,
the allowed characters default to POSIX "fully portable filename" standards
with the addition of spaces:
.IR "[A-Za-z0-9 ._-]" .
Spaces can be disabled by setting
.B ALLOW_SPACES
to 0 in
.IR config.h .
.
.TP
.B dd
Delete current selection (does not touch marked files).
This will copy the file/directory into the
.B CFM_TMP
directory and can be undone with
.BR u .
If the
.B CFM_TMP
directory does not exist, deletions will be permanent.
.
.TP
.B alt+dd
Permanently delete current selection (does not touch marked files) without
backing up for undo like
.B dd
does.
This is useful for large directories where a copy will take a long time.
.
.TP
.B m Space
Toggle mark for deletion.
.
.TP
.B D
Delete all marked files (does not touch unmarked files).
.
.TP
.B u
Undo the last deletion operation (does not work if
.B cfm
was unable to create or access its trash directory, in which case deletion is permanent).
.
.TP
.B X
Cut the selected file or directory (can be pasted again with
.BR p ).
Not available if the tmp directory is not available.
.
.TP
.B yy
Copy the selected file or directory (can be pasted again with
.BR p ).
.
.TP
.B p
Paste the previously cut or copied file or directory; shared between all views.
.
.TP
.B TAB
Switches to the next view.
.
.TP
.B \`
Switches to the previous view.
.
.TP
.B 1\(en0
Switches to view
.IR N ,
up to the number specified by
.B VIEW_COUNT
(2 by default).
.
.TP
.B q ESC
Quit
.BR cfm .
.
.TP
.B Q
Quit
.BR cfm ,
saving its working directory to the file specified in
.BR CD_ON_CLOSE ,
if enabled, or the
.B CFM_CD_ON_CLOSE
environment variable if not.
.
.SH SCRIPTING
If stdin or stdout are not attached to a TTY,
.B cfm
will read commands from stdin and quit at EOF, skipping all drawing.
Any errors are fatal and will be printed to stderr.
Note that in non-interactive mode,
.B cfm
will
.B NOT
backup files when deleting.
All deletions will be permanent.
.
.SH AUTHOR
Will Eccles \(lawill@eccles.dev\(ra.
For more information, see the
.UR https://github.com/willeccles/cfm
GitHub repo
.UE .
