.TH CFM 1 "2020 January 29" "" ""

.SH NAME
cfm \- cactus file manager

.SH SYNOPSIS
.B cfm
.RI [ DIR ]

.SH DESCRIPTION
.B cfm
is a simple, clean, fast file TUI manager.

.SH OPTIONS
.TP
.BR DIR
Directory to open
.B cfm
in, or the working directory if not specified.

.SH CONFIGURATION
Copy \fIconfig.def.h\fR to \fIconfig.h\fR and modify as needed to configure at
build-time. By default,
.B cfm
will attempt to read the \fIEDITOR\fR, \fISHELL\fR, and \fIOPENER\fR environment
variables. If it is preferable for
.B cfm
to use a different value for any of these, it can be specified by prepending
\fICFM_\fR to any of the variables.

.SH USAGE
Note: arrow keys work the same as hjkl.
.TP
.BI "j k"
Move up/down

.TP
.BI "h l"
Move left/right

.TP
.BI gg
Move to top

.TP
.BI G
Move to bottom

.TP
.BI l
Open file using \fIEDITOR\fR, or change into directory

.TP
.BI o
Open file or directory with \fIOPENER\fR

.TP
.BI RET
Works like
.BI o
if \fIENTER_OPENS\fR is enabled, else works like
.BI l

.TP
.BI .
Toggles visibility of dotfiles

.TP
.BI e
Open file or directory in \fIEDITOR\fR

.TP
.BI r
Reload directory

.TP
.BI S
Spawn a shell (defined by \fISHELL\fR) in a directory

.TP
.BI T
Create a new file, opening \fIEDITOR\fR to enter a filename

.TP
.BI M
Create a new directory, opening \fIEDITOR\fR to enter a directory name

Note: for both
.BI T
and
.BI M
, the allowed characters default to POSIX "fully portable filename" standards
with the addition of spaces: \fI[A-Za-z0-9 ._-]\fR. Spaces can be disabled by
setting \fIALLOW_SPACES\fR to 0 in \fIconfig.h\fR.

.TP
.BI R
Rename a file by opening \fIEDITOR\fR to edit the filename

.TP
.BI dd
Delete current selection (does not touch marked files)

.TP
.BI m
Toggle mark for deletion

.TP
.BI D
Delete all marked files (does not touch unmarked files)

.TP
.BI u
Undo the last deletion operation (does not work if
.B cfm
was unable to create or access its trash directory, in which case deletion is permanent)

.TP
.BI TAB
Switches to the next view

.TP
.BI `
Switches to the previous view

.TP
.BI "1\-0"
Switches to view N, up to the number specified by \fIVIEW_COUNT\fR (2 by default)

.TP
.BI "q ESC"
Quit
.B cfm

.SH AUTHOR
Will Eccles <will@eccles.dev>.
For more information, see https://github.com/willeccles/cfm.
